config/routes.rb
Rails.application.routes.draw do
  resources :customers
  root 'customers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: [:show, :edit, :update, :destroy]

    def index
        @customers = Customer.all
    end

    def show
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(customer_params)

        if @customer.save
            redirect_to customers_path, notice: "Cliente criado com sucesso."
        else 
            render :new
        end
    end

    def edit 
    end

    def update
        if @customer.update(customer_params)
            redirect_to customers_path, notice: "Cliente atualizado com sucesso."
        else
            render :edit
        end
    end

    def destroy
        @customer.destroy
            redirect_to customers_path, notice: "Cliente removido com sucesso."
    end

    private 

    def set_customer
        @customer = Customer.find (params[:id])
    end

    def customer_params
        params.require(:customer).permit(:name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <%= form.submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to "Visualizar Detalhes", edit_customer_path(@customer) %>
<%= link_to "Voltar", customers_path %>

app/views/customers/index.html.erb
<h1>Clientes</h1>

<table>
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
    </tr>

    <% @customers.each do |customer| %>
        <tr>
            <td><%= customer.name  %></td>
            <td><%= custumer.email %></td>
            <td><%= customer.phone %></td>
        </tr>
    <% end %>
</table>

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>

    <%= form_with(model: @customer, local: true) do |form| %>
        <%= render 'form', form: form %> 
        <%= form.submit "Salvar" %>
        <% end %>

app/views/customers/show.html.erb
<h1>Dados do Cliente</h1>

<p><strong>Nome:</strong> <%= @customer.name %></p>
<p><strong>Email:</strong> <%= @customer.email %></p>
<p><strong>Telefone:</strong> <%= @customer.phone %></p>

<%= link_to "Editar", edit_customer_path(@customer) %> |
<%= link_to "Voltar", edit_customer_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>